/**
 * Build-time generator: reads the TypeScript template and produces
 * `commands/tools.sh` — the shell heredoc wrapper that outputs the
 * tools file at SSH runtime.
 *
 * Usage:
 *   node --import tsx/esm src/commands/generate-tools-sh.ts
 *
 * The generated shell script uses two heredoc styles:
 *   - TOOLS_DYNAMIC (unquoted) — shell expands $HOST, $PORT, $SOURCES
 *   - 'TOOLS_STATIC' (quoted)  — no shell expansion, TypeScript literal
 */

import * as fs from "node:fs";
import * as path from "node:path";
import {
  DYNAMIC_HEADER,
  STATIC_BODY,
  SEARCH_DESCRIPTION_PREFIX,
  SEARCH_DESCRIPTION_DYNAMIC,
  SEARCH_BODY_STATIC,
  REMAINING_TOOLS,
} from "./tools-template.js";

const HEADER = `\
#!/bin/sh
# AUTO-GENERATED by src/commands/generate-tools-sh.ts — do not edit manually.
# Edit src/commands/tools-template.ts instead, then run: pnpm generate:tools
#
# Outputs a complete OpenCode custom tools file.
# Usage: ssh -p 2222 docs@HOST tools > .opencode/tools/docs.ts

HOST="\${DOCS_SSH_HOST:-localhost}"
PORT="\${DOCS_SSH_PORT:-2222}"
SOURCES=$(ls -1 /docs/ | grep -v '_index' | tr '\\n' ', ' | sed 's/,$//' | sed 's/,/, /g')
`;

/**
 * Escapes a TypeScript string for embedding in a shell heredoc.
 * In a quoted heredoc ('EOF'), backslashes are literal. But we still
 * need to ensure the heredoc delimiter doesn't appear in the content.
 */
function forQuotedHeredoc(ts: string): string {
  // The template already handles its own escaping since it's written
  // as template literal strings. We just need to make sure the
  // TOOLS_STATIC delimiter doesn't appear in the content.
  return ts;
}

/**
 * Converts the {{placeholder}} syntax in the dynamic header to
 * shell variable references for unquoted heredoc expansion.
 */
function toDynamicShell(template: string): string {
  return template
    .replace("{{SSH_HOST}}", 'docs@${HOST}')
    .replace("{{SSH_PORT}}", "${PORT}");
}

/**
 * Converts the search description placeholder to a shell-expanded version.
 */
function toSearchToolShell(template: string, descPrefix: string): string {
  const shellDesc = descPrefix.replace("{{SOURCES}}", "${SOURCES}");
  return template.replace("{{SEARCH_DESCRIPTION}}", shellDesc);
}

function generate(): string {
  const parts: string[] = [HEADER];

  // Dynamic header (shell expands HOST/PORT)
  parts.push(`cat << TOOLS_DYNAMIC`);
  parts.push(toDynamicShell(DYNAMIC_HEADER));
  parts.push(`TOOLS_DYNAMIC`);
  parts.push(``);

  // Static body (no shell expansion)
  parts.push(`cat << 'TOOLS_STATIC'`);
  parts.push(forQuotedHeredoc(STATIC_BODY));
  parts.push(`TOOLS_STATIC`);
  parts.push(``);

  // Search tool description (dynamic — SOURCES expansion by shell)
  parts.push(`cat << TOOLS_DYNAMIC`);
  parts.push(toSearchToolShell(SEARCH_DESCRIPTION_DYNAMIC, SEARCH_DESCRIPTION_PREFIX));
  parts.push(`TOOLS_DYNAMIC`);
  parts.push(``);

  // Search tool body (static — has backtick templates with $/{}/| chars)
  parts.push(`cat << 'TOOLS_STATIC'`);
  parts.push(forQuotedHeredoc(SEARCH_BODY_STATIC));
  parts.push(`TOOLS_STATIC`);
  parts.push(``);

  // Remaining tools (static)
  parts.push(`cat << 'TOOLS_STATIC'`);
  parts.push(forQuotedHeredoc(REMAINING_TOOLS));
  parts.push(`TOOLS_STATIC`);

  return parts.join("\n");
}

// ─── Main ──────────────────────────────────────────────────────────

const outPath = path.resolve(
  import.meta.dirname,
  "../../commands/tools.sh",
);

const content = generate();
fs.writeFileSync(outPath, content, { mode: 0o755 });

const lines = content.split("\n").length;
console.log(`Generated ${outPath} (${lines} lines)`);
