/**
 * Build-time generator: reads the TypeScript template and produces
 * `commands/tools.sh` — the shell heredoc wrapper that outputs the
 * tools file at SSH runtime.
 *
 * Usage:
 *   node --import tsx/esm src/commands/generate-tools-sh.ts
 *
 * The generated shell script uses two heredoc styles:
 *   - TOOLS_DYNAMIC (unquoted) — shell expands $HOST, $PORT, $SOURCES
 *   - 'TOOLS_STATIC' (quoted)  — no shell expansion, TypeScript literal
 */

import * as fs from "node:fs";
import * as path from "node:path";
import {
  DYNAMIC_HEADER,
  STATIC_BODY,
  SEARCH_DESCRIPTION,
  SEARCH_BODY_STATIC,
  REMAINING_TOOLS,
} from "./tools-template.js";

const HEADER = `\
#!/bin/sh
# AUTO-GENERATED by src/commands/generate-tools-sh.ts — do not edit manually.
# Edit src/commands/tools-template.ts instead, then run: pnpm generate:tools
#
# Outputs a complete OpenCode custom tools file.
# Usage: ssh -p 2222 docs@HOST tools > .opencode/tools/docs.ts

HOST="\${DOCS_SSH_HOST:-localhost}"
PORT="\${DOCS_SSH_PORT:-2222}"
`;

/**
 * Escapes a TypeScript string for embedding in a shell heredoc.
 * In a quoted heredoc ('EOF'), backslashes are literal. The only
 * correctness concern is that the delimiter ('TOOLS_STATIC') must not
 * appear on its own line inside the content — if it did, the shell
 * would close the heredoc early and the rest of the template would
 * execute as shell commands. This guard throws at build time so the
 * footgun fails the CI "Verify tools.sh is in sync" step instead of
 * silently corrupting the generated script.
 */
export function forQuotedHeredoc(ts: string): string {
  if (
    ts.includes("\nTOOLS_STATIC\n") ||
    ts.startsWith("TOOLS_STATIC\n") ||
    ts.endsWith("\nTOOLS_STATIC") ||
    ts === "TOOLS_STATIC"
  ) {
    throw new Error(
      "tools-template content contains heredoc delimiter 'TOOLS_STATIC' on its own line — " +
        "this would prematurely close the generated shell heredoc. Rename the delimiter in " +
        "generate-tools-sh.ts or rewrite the template content.",
    );
  }
  return ts;
}

/**
 * Converts the {{placeholder}} syntax in the dynamic header to
 * shell variable references for unquoted heredoc expansion.
 */
function toDynamicShell(template: string): string {
  return template
    .replace("{{SSH_HOST}}", 'docs@${HOST}')
    .replace("{{SSH_PORT}}", "${PORT}");
}

export function generate(): string {
  const parts: string[] = [HEADER];

  // Dynamic header (shell expands HOST/PORT)
  parts.push(`cat << TOOLS_DYNAMIC`);
  parts.push(toDynamicShell(DYNAMIC_HEADER));
  parts.push(`TOOLS_DYNAMIC`);
  parts.push(``);

  // Static body (no shell expansion)
  parts.push(`cat << 'TOOLS_STATIC'`);
  parts.push(forQuotedHeredoc(STATIC_BODY));
  parts.push(`TOOLS_STATIC`);
  parts.push(``);

  // Search tool description (static — no dynamic vars needed)
  parts.push(`cat << 'TOOLS_STATIC'`);
  parts.push(forQuotedHeredoc(SEARCH_DESCRIPTION));
  parts.push(`TOOLS_STATIC`);
  parts.push(``);

  // Search tool body (static — has backtick templates with $/{}/| chars)
  parts.push(`cat << 'TOOLS_STATIC'`);
  parts.push(forQuotedHeredoc(SEARCH_BODY_STATIC));
  parts.push(`TOOLS_STATIC`);
  parts.push(``);

  // Remaining tools (static)
  parts.push(`cat << 'TOOLS_STATIC'`);
  parts.push(forQuotedHeredoc(REMAINING_TOOLS));
  parts.push(`TOOLS_STATIC`);

  return parts.join("\n");
}

// ─── Main ──────────────────────────────────────────────────────────
// Only runs when invoked as a script (pnpm generate:tools), not on import.
// argv[1] is the entry script; compare against import.meta.url.

const invokedAsScript = import.meta.url === `file://${process.argv[1]}`;

if (invokedAsScript) {
  const outPath = path.resolve(
    import.meta.dirname,
    "../../commands/tools.sh",
  );

  const content = generate();
  fs.writeFileSync(outPath, content, { mode: 0o755 });

  const lines = content.split("\n").length;
  console.log(`Generated ${outPath} (${lines} lines)`);
}
