/**
 * Build-time generator: reads the Pi extension template and produces
 * `commands/tools-pi.sh` — the shell heredoc wrapper that outputs the
 * extension file at SSH runtime.
 *
 * Usage:
 *   node --import tsx/esm src/commands/generate-tools-pi-sh.ts
 *
 * The generated shell script uses two heredoc styles:
 *   - PI_DYNAMIC (unquoted) — shell expands $HOST, $PORT
 *   - 'PI_STATIC' (quoted)  — no shell expansion, TypeScript literal
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { PI_DYNAMIC_HEADER, PI_STATIC_BODY } from "./tools-pi-template.js";

const HEADER = `\
#!/bin/sh
# AUTO-GENERATED by src/commands/generate-tools-pi-sh.ts — do not edit manually.
# Edit src/commands/tools-pi-template.ts instead, then run: pnpm generate:tools
#
# Outputs a Pi extension file (TypeBox / @earendil-works/pi-coding-agent).
# Usage: ssh -p 2222 docs@HOST tools pi > ~/.pi/agent/extensions/docs.ts

HOST="\${DOCS_SSH_HOST:-localhost}"
PORT="\${DOCS_SSH_PORT:-2222}"
`;

/**
 * Guards against heredoc delimiter collision with PI_STATIC.
 */
export function forQuotedHeredoc(ts: string): string {
  if (
    ts.includes("\nPI_STATIC\n") ||
    ts.startsWith("PI_STATIC\n") ||
    ts.endsWith("\nPI_STATIC") ||
    ts === "PI_STATIC"
  ) {
    throw new Error(
      "tools-pi-template content contains heredoc delimiter 'PI_STATIC' on its own line — " +
        "this would prematurely close the generated shell heredoc. Rename the delimiter.",
    );
  }
  return ts;
}

function toDynamicShell(template: string): string {
  return template
    .replace("{{SSH_HOST}}", 'docs@${HOST}')
    .replace("{{SSH_PORT}}", "${PORT}");
}

export function generate(): string {
  const parts: string[] = [HEADER];

  // Dynamic header (shell expands HOST/PORT)
  parts.push(`cat << PI_DYNAMIC`);
  parts.push(toDynamicShell(PI_DYNAMIC_HEADER));
  parts.push(`PI_DYNAMIC`);
  parts.push(``);

  // Static body (no shell expansion — TypeScript has $ chars everywhere)
  parts.push(`cat << 'PI_STATIC'`);
  parts.push(forQuotedHeredoc(PI_STATIC_BODY));
  parts.push(`PI_STATIC`);

  return parts.join("\n");
}

// ─── Main ──────────────────────────────────────────────────────────

const invokedAsScript = import.meta.url === `file://${process.argv[1]}`;

if (invokedAsScript) {
  const outPath = path.resolve(
    import.meta.dirname,
    "../../commands/tools-pi.sh",
  );

  const content = generate();
  fs.writeFileSync(outPath, content, { mode: 0o755 });

  const lines = content.split("\n").length;
  console.log(`Generated ${outPath} (${lines} lines)`);
}
